#!/bin/bash

#Russ Ferriday, Topia Systems Ltd, russf@topia.com

### BEGIN INIT INFO
# Provides:          plone4
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the plone content management system
# Description:       starts plone using start-stop-daemon
### END INIT INFO

## -- Usage notes for installing this file into start/stop tree
## link this file into the startup tree at /etc/init.d/plone4
#ln -s /home/plone/Plone4/zeocluster/bin/plone /etc/init.d/plone4
## automatically create the start and kill links for each level
#/usr/sbin/update-rc.d -f plone4 defaults

su -c "/home/plone/Plone4/zeocluster/bin/plonectl $@ " plone

